library(USvac)
data(ALL_df_S)

#----Fig S6 CHR plot
Daily_hospital_Admission_pct_ma_plot <- function(State) {
  
  State_df<-ALL_df[which(ALL_df$State==State),]
  time = 1:nrow(State_df)
  Date<- State_df$Date
  actual_case<-State_df$Daily_hospital_Admission_pct_ma
  plot(time,actual_case,pch=16,xaxt = "n",col="white",ylim = c(0,26), yaxt = "n",
       xlab= "", ylab="",main=State,cex.main=1.2,cex.lab=1.2) 
  abline(v=168,lty=2,col="red")
  lines(State_df$Daily_hospital_Admission_pct_ma, lwd = 1, col ="black")  
  axis(1,at =seq(1,nrow(State_df),10),labels = Date[seq(1,nrow(State_df),10)],las = 2,cex.axis=1.1)
  axis(2,las = 1,cex.axis = 1.2,cex.axis=1.1) 
  
}

#pdf('.../Fig S6.pdf', height = 20, width = 23)
par(mfrow=c(7,8))
Daily_hospital_Admission_pct_ma_plot("Alabama")
Daily_hospital_Admission_pct_ma_plot("Alaska")
Daily_hospital_Admission_pct_ma_plot("Arizona")
Daily_hospital_Admission_pct_ma_plot("Arkansas")
Daily_hospital_Admission_pct_ma_plot("California")
Daily_hospital_Admission_pct_ma_plot("Colorado")
Daily_hospital_Admission_pct_ma_plot("Connecticut")
Daily_hospital_Admission_pct_ma_plot("Delaware")
Daily_hospital_Admission_pct_ma_plot("District of Columbia")
Daily_hospital_Admission_pct_ma_plot("Florida")
Daily_hospital_Admission_pct_ma_plot("Georgia")
Daily_hospital_Admission_pct_ma_plot("Hawaii")
Daily_hospital_Admission_pct_ma_plot("Idaho")
Daily_hospital_Admission_pct_ma_plot("Illinois")
Daily_hospital_Admission_pct_ma_plot("Indiana")
Daily_hospital_Admission_pct_ma_plot("Iowa")
Daily_hospital_Admission_pct_ma_plot("Kansas")
Daily_hospital_Admission_pct_ma_plot("Kentucky")
Daily_hospital_Admission_pct_ma_plot("Louisiana")
Daily_hospital_Admission_pct_ma_plot("Maine")
Daily_hospital_Admission_pct_ma_plot("Maryland")
Daily_hospital_Admission_pct_ma_plot("Massachusetts")
Daily_hospital_Admission_pct_ma_plot("Michigan")
Daily_hospital_Admission_pct_ma_plot("Minnesota")
Daily_hospital_Admission_pct_ma_plot("Mississippi")
Daily_hospital_Admission_pct_ma_plot("Missouri")
Daily_hospital_Admission_pct_ma_plot("Montana")
Daily_hospital_Admission_pct_ma_plot("Nebraska")
Daily_hospital_Admission_pct_ma_plot("Nevada")
Daily_hospital_Admission_pct_ma_plot("New Hampshire")
Daily_hospital_Admission_pct_ma_plot("New Jersey")
Daily_hospital_Admission_pct_ma_plot("New Mexico")
Daily_hospital_Admission_pct_ma_plot("New York")
Daily_hospital_Admission_pct_ma_plot("North Carolina")
Daily_hospital_Admission_pct_ma_plot("North Dakota")
Daily_hospital_Admission_pct_ma_plot("Ohio")
Daily_hospital_Admission_pct_ma_plot("Oklahoma")
Daily_hospital_Admission_pct_ma_plot("Oregon")
Daily_hospital_Admission_pct_ma_plot("Pennsylvania")
Daily_hospital_Admission_pct_ma_plot("Rhode Island")
Daily_hospital_Admission_pct_ma_plot("South Carolina")
Daily_hospital_Admission_pct_ma_plot("South Dakota")
Daily_hospital_Admission_pct_ma_plot("Tennessee")
Daily_hospital_Admission_pct_ma_plot("Texas")
Daily_hospital_Admission_pct_ma_plot("Utah")
Daily_hospital_Admission_pct_ma_plot("Vermont")
Daily_hospital_Admission_pct_ma_plot("Virginia")
Daily_hospital_Admission_pct_ma_plot("Washington")
Daily_hospital_Admission_pct_ma_plot("West Virginia")
Daily_hospital_Admission_pct_ma_plot("Wisconsin")
Daily_hospital_Admission_pct_ma_plot("Wyoming")
#dev.off()