library(USvac)
data(ALL_df_S)

#----Fig S4 RH plot
RH_plot <- function(State) {
  
  State_df<-ALL_df_S[which(ALL_df_S$State==State),]
  time = 1:nrow(State_df)
  Date<- State_df$Date
  actual_case<-State_df$Humidity_14MA
  plot(time,actual_case,pch=16,xaxt = "n",col="white",ylim = c(22,91), yaxt = "n",
       xlab= "", ylab="",main=State,cex.main=1.2,cex.lab=1.2) 
  lines(State_df$Humidity_14MA, lwd = 1, col ="black")  
  axis(1,at =seq(1,nrow(State_df),10),labels = Date[seq(1,nrow(State_df),10)],las = 2,cex.axis=1.1)
  axis(2,las = 1,cex.axis = 1.2,cex.axis=1.1) 
  
}

#pdf('.../Fig S4.pdf', height = 20, width = 23)
par(mfrow=c(7,8))
RH_plot("Alabama")
RH_plot("Alaska")
RH_plot("Arizona")
RH_plot("Arkansas")
RH_plot("California")
RH_plot("Colorado")
RH_plot("Connecticut")
RH_plot("Delaware")
RH_plot("District of Columbia")
RH_plot("Florida")
RH_plot("Georgia")
RH_plot("Hawaii")
RH_plot("Idaho")
RH_plot("Illinois")
RH_plot("Indiana")
RH_plot("Iowa")
RH_plot("Kansas")
RH_plot("Kentucky")
RH_plot("Louisiana")
RH_plot("Maine")
RH_plot("Maryland")
RH_plot("Massachusetts")
RH_plot("Michigan")
RH_plot("Minnesota")
RH_plot("Mississippi")
RH_plot("Missouri")
RH_plot("Montana")
RH_plot("Nebraska")
RH_plot("Nevada")
RH_plot("New Hampshire")
RH_plot("New Jersey")
RH_plot("New Mexico")
RH_plot("New York")
RH_plot("North Carolina")
RH_plot("North Dakota")
RH_plot("Ohio")
RH_plot("Oklahoma")
RH_plot("Oregon")
RH_plot("Pennsylvania")
RH_plot("Rhode Island")
RH_plot("South Carolina")
RH_plot("South Dakota")
RH_plot("Tennessee")
RH_plot("Texas")
RH_plot("Utah")
RH_plot("Vermont")
RH_plot("Virginia")
RH_plot("Washington")
RH_plot("West Virginia")
RH_plot("Wisconsin")
RH_plot("Wyoming")
#dev.off()
