library(USvac)
data(ALL_df_S)
#----Fig S3 Temp plot
Temp_plot <- function(State) {

  State_df<-ALL_df_S[which(ALL_df_S$State==State),]
  time = 1:nrow(State_df)
  Date<- State_df$Date
  actual_case<-State_df$TEMP_new_14MA
  plot(time,actual_case,pch=16,xaxt = "n",col="white",ylim = c(-22,23), yaxt = "n",
       xlab= "", ylab="",main=State,cex.main=1.2,cex.lab=1.2) 
  lines(State_df$TEMP_new_14MA, lwd = 1, col ="black")  
  axis(1,at =seq(1,nrow(State_df),10),labels = Date[seq(1,nrow(State_df),10)],las = 2,cex.axis=1.1)
  axis(2,las = 1,cex.axis = 1.2,cex.axis=1.1) 
  
}

#pdf('.../Fig S3.pdf', height = 20, width = 23)
par(mfrow=c(7,8))
Temp_plot("Alabama")
Temp_plot("Alaska")
Temp_plot("Arizona")
Temp_plot("Arkansas")
Temp_plot("California")
Temp_plot("Colorado")
Temp_plot("Connecticut")
Temp_plot("Delaware")
Temp_plot("District of Columbia")
Temp_plot("Florida")
Temp_plot("Georgia")
Temp_plot("Hawaii")
Temp_plot("Idaho")
Temp_plot("Illinois")
Temp_plot("Indiana")
Temp_plot("Iowa")
Temp_plot("Kansas")
Temp_plot("Kentucky")
Temp_plot("Louisiana")
Temp_plot("Maine")
Temp_plot("Maryland")
Temp_plot("Massachusetts")
Temp_plot("Michigan")
Temp_plot("Minnesota")
Temp_plot("Mississippi")
Temp_plot("Missouri")
Temp_plot("Montana")
Temp_plot("Nebraska")
Temp_plot("Nevada")
Temp_plot("New Hampshire")
Temp_plot("New Jersey")
Temp_plot("New Mexico")
Temp_plot("New York")
Temp_plot("North Carolina")
Temp_plot("North Dakota")
Temp_plot("Ohio")
Temp_plot("Oklahoma")
Temp_plot("Oregon")
Temp_plot("Pennsylvania")
Temp_plot("Rhode Island")
Temp_plot("South Carolina")
Temp_plot("South Dakota")
Temp_plot("Tennessee")
Temp_plot("Texas")
Temp_plot("Utah")
Temp_plot("Vermont")
Temp_plot("Virginia")
Temp_plot("Washington")
Temp_plot("West Virginia")
Temp_plot("Wisconsin")
Temp_plot("Wyoming")
#dev.off()
