library(USvac)
data(ALL_df_S)

#---- Fig S2 Vac coverage
Comp_vac_plot <- function(State) {
  
  #State<-"Alabama"
  # plot daily cases---------------------
  State_df<-ALL_df_S[which(ALL_df_S$State==State),]
  time = 1:nrow(State_df)
  Date<- State_df$Date
  actual_case<-State_df$Adjust_Doses_Vax_Pct
  plot(time,actual_case,pch=16,xaxt = "n",col="white",ylim = c(42,77), yaxt = "n",
       xlab= "", ylab="",main=State,cex.main=1.2,cex.lab=1.2) 
  lines(State_df$Adjust_Doses_Vax_Pct, lwd = 1, col ="black")  
  axis(1,at =seq(1,nrow(State_df),10),labels = Date[seq(1,nrow(State_df),10)],las = 2,cex.axis=1.1)
  axis(2,las = 1,cex.axis = 1.2,cex.axis=1.1) 
  
}

#pdf('.../Fig S2.pdf', height = 20, width = 23)
par(mfrow=c(7,8))
Comp_vac_plot("Alabama")
Comp_vac_plot("Alaska")
Comp_vac_plot("Arizona")
Comp_vac_plot("Arkansas")
Comp_vac_plot("California")
Comp_vac_plot("Colorado")
Comp_vac_plot("Connecticut")
Comp_vac_plot("Delaware")
Comp_vac_plot("District of Columbia")
Comp_vac_plot("Florida")
Comp_vac_plot("Georgia")
Comp_vac_plot("Hawaii")
Comp_vac_plot("Idaho")
Comp_vac_plot("Illinois")
Comp_vac_plot("Indiana")
Comp_vac_plot("Iowa")
Comp_vac_plot("Kansas")
Comp_vac_plot("Kentucky")
Comp_vac_plot("Louisiana")
Comp_vac_plot("Maine")
Comp_vac_plot("Maryland")
Comp_vac_plot("Massachusetts")
Comp_vac_plot("Michigan")
Comp_vac_plot("Minnesota")
Comp_vac_plot("Mississippi")
Comp_vac_plot("Missouri")
Comp_vac_plot("Montana")
Comp_vac_plot("Nebraska")
Comp_vac_plot("Nevada")
Comp_vac_plot("New Hampshire")
Comp_vac_plot("New Jersey")
Comp_vac_plot("New Mexico")
Comp_vac_plot("New York")
Comp_vac_plot("North Carolina")
Comp_vac_plot("North Dakota")
Comp_vac_plot("Ohio")
Comp_vac_plot("Oklahoma")
Comp_vac_plot("Oregon")
Comp_vac_plot("Pennsylvania")
Comp_vac_plot("Rhode Island")
Comp_vac_plot("South Carolina")
Comp_vac_plot("South Dakota")
Comp_vac_plot("Tennessee")
Comp_vac_plot("Texas")
Comp_vac_plot("Utah")
Comp_vac_plot("Vermont")
Comp_vac_plot("Virginia")
Comp_vac_plot("Washington")
Comp_vac_plot("West Virginia")
Comp_vac_plot("Wisconsin")
Comp_vac_plot("Wyoming")
#dev.off()
