library(dlnm)
library(splines)
library(AICcmodavg)
library(fmsb)
library(zoo)
library(e1071)
library(hydroGOF)
library(splines)
library(ggplot2)
library(MLmetrics)
library(rlang)

library("lme4")
library("merTools")
library(MuMIn)
Sys.setlocale("LC_TIME", "en_US")

library(USvac)
data(extdata)
model_fitting("Basic model",extdata)
model_fitting("Mediation model",extdata)
